server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    etag off;

    location ^~ /realms/ {
        proxy_pass http://keycloak:8080/realms/;
        proxy_http_version 1.1;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_cookie_flags ~ nosecure;
    }

    location ^~ /admin/ {
        proxy_pass http://keycloak:8080/admin/;
        proxy_http_version 1.1;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location ^~ /resources/ {
        proxy_pass http://keycloak:8080/resources/;
        proxy_http_version 1.1;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location ^~ /api/ {
        proxy_pass http://max-auth:8025/api/;
        proxy_http_version 1.1;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /assets/ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        try_files $uri =404;
    }

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        try_files /index.html =404;
    }

    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        try_files $uri $uri/ /index.html;
    }
}
